spring.application.name=restaurantservice
spring.datasource.url=jdbc:postgresql://localhost:5432/grabit
spring.datasource.username=db_user_123
spring.datasource.password=db_password_@_1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# --- Eureka settings ---
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka


server.port=8081

server.servlet.context-path=

